#!/bin/bash
mkdir -p ~/bin
cd ~/bin

if [ ! -e composer ]; then
echo Installing composer...
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '55d6ead61b29c7bdee5cccfb50076874187bd9f21f65d8991d46ec5cc90518f447387fb9f76ebae1fbbacf329e583e30') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar composer
chmod a+x composer
else
echo Composer already there...
fi

if ! [[ ":$PATH:" == *":$HOME/.composer/vendor/bin:"* ]]; then
echo Setting path...
export PATH=$PATH:$HOME/.composer/vendor/bin
else
echo Path already set...
fi

if [ ! -e $HOME/.mmmrc ]; then
echo Installing .mmmrc...
cat <<'EOD' > $HOME/.mmmrc
PATH=$PATH:$HOME/.composer/vendor/bin
EOD
echo '. $HOME/.mmmrc' >>$HOME/.bashrc
else
echo .mmmrc already there...
fi

if ! which cgr ; then
echo Installing CGR...
composer global require consolidation/cgr
else
echo CGR already there...
fi

if ! which drush ; then
echo Installing drush...
cgr drush/drush
drush init -y

# Fixup prompt
cat <<'EOD' >>~/.drush/drush.prompt.sh

# MM Customizations
unset PROMPT_COMMAND;
export PS1='\u@\h \w$(__git_ps1 " (%s)")$(__drush_ps1 "[%s]")\$ '
EOD

else
echo Drush already there...
fi

if ! which mm-prepare-server ; then
echo Installing mmtools...
cgr clever-systems/mmtools --stability dev
mm-prepare-server
else
echo MMTools already there...
fi

if [ ! -e ~/.drush/mmtools ]; then
echo Linking mmtools...
mkdir -p ~/.drush
ln -s ~/.composer/global/clever-systems/mmtools ~/.drush
fi