#!/bin/bash
mkdir -p ~/bin
cd ~/bin

if [ ! -e composer ]; then
echo Installing composer...
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar composer
chmod a+x composer
else
echo Composer already there...
fi

if ! [[ ":$PATH:" == *":$HOME/.composer/vendor/bin:"* ]]; then
echo Setting path...
export PATH=$PATH:$HOME/.composer/vendor/bin
else
echo Path already set...
fi

if [ ! -e $HOME/.mmmrc ]; then
echo Installing .mmmrc...
cat <<'EOD' > $HOME/.mmmrc
PATH=$PATH:$HOME/.composer/vendor/bin
EOD
echo '. $HOME/.mmmrc' >>$HOME/.bashrc
else
echo .mmmrc already there...
fi

if [[ ! $(composer global show bamarni/composer-bin-plugin) ]] ; then
echo Installing composer bin plugin...
composer global require bamarni/composer-bin-plugin
else
echo composer bin plugin already there...
fi

if [[ ! $(composer global show hirak/prestissimo) ]] ; then
echo Installing composer prestissimo...
composer global require hirak/prestissimo
else
echo composer prestissimo already there...
fi

if ! which drush ; then
echo Installing drush...
composer global bin drush require drush/drush:^8
drush init -y

# Fixup prompt
cat <<'EOD' >>~/.drush/drush.prompt.sh

# MM Customizations
unset PROMPT_COMMAND;
export PS1='\u@\h \w$(__git_ps1 " (%s)")$(__drush_ps1 "[%s]")\$ '
EOD

else
echo Drush already there...
fi

if ! which mm-prepare-server ; then
echo Installing mmtools...
composer global bin mmtools require machbarmacher/mmtools --stability dev
mm-prepare-server
else
echo MMTools already there...
fi

if [ ! -e ~/.drush/mmtools ]; then
echo Linking mmtools...
mkdir -p ~/.drush
ln -sf ~/.composer/vendor-bin/mmtools/vendor/machbarmacher/mmtools ~/.drush
fi
